// Code generated by "stringer -type=opcode"; DO NOT EDIT.

package mmr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNSPECIFIED-0]
	_ = x[PUSHPOS-1]
	_ = x[PUSHVAL-2]
	_ = x[PUSHEMPTY-3]
	_ = x[POP-4]
}

const _opcode_name = "UNSPECIFIEDPUSHPOSPUSHVALPUSHEMPTYPOP"

var _opcode_index = [...]uint8{0, 11, 18, 25, 34, 37}

func (i opcode) String() string {
	if i < 0 || i >= opcode(len(_opcode_index)-1) {
		return "opcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _opcode_name[_opcode_index[i]:_opcode_index[i+1]]
}
