// Code generated by "stringer -type=OpCode"; DO NOT EDIT.

package mmr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNSPECIFIED-0]
	_ = x[PUSHPOS-1]
	_ = x[PUSHINPUT-2]
	_ = x[POP-3]
}

const _OpCode_name = "UNSPECIFIEDPUSHPOSPUSHINPUTPOP"

var _OpCode_index = [...]uint8{0, 11, 18, 27, 30}

func (i OpCode) String() string {
	if i < 0 || i >= OpCode(len(_OpCode_index)-1) {
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[i]:_OpCode_index[i+1]]
}
